/**
 * Yan #41: CSV/PDF export label catalog. Exports were EN-only — TR users
 * downloaded reports with English column headers. Locale resolves from
 * `req.user.locale` first (when populated by an auth middleware in the
 * future), then `Accept-Language`, then defaults to `en`.
 */
import type { Request } from 'express';

export type ExportLocale = 'tr' | 'en';

interface ExportLabels {
  // CSV column headers
  timestamp: string;
  camera: string;
  peopleIn: string;
  peopleOut: string;
  currentCount: string;
  queueCount: string;
  avgWaitTime: string;
  longestWaitTime: string;
  fps: string;
  // PDF section labels + summary fields
  pdfTitle: string;
  generatedDate: string;
  cameraField: string;
  periodField: string;
  totalRecordsField: string;
  allCameras: string;
  allTime: string;
  now: string;
  summarySection: string;
  totalEntered: string;
  totalExited: string;
  avgCurrent: string;
  avgQueue: string;
  detailSection: string;
  detailTimestamp: string;
  detailPeopleIn: string;
  detailPeopleOut: string;
  detailCurrent: string;
  detailQueue: string;
  detailAvgWait: string;
  detailMaxWait: string;
  detailFps: string;
  moreRecords: (n: number) => string;
  footer: string;
  // Filename slug
  csvFilename: (date: string) => string;
  pdfFilename: (date: string) => string;
}

export const EXPORT_LABELS: Record<ExportLocale, ExportLabels> = {
  tr: {
    timestamp: 'Tarih',
    camera: 'Kamera',
    peopleIn: 'Giren',
    peopleOut: 'Cikan',
    currentCount: 'Anlik Sayi',
    queueCount: 'Kuyruk',
    avgWaitTime: 'Ort. Bekleme (sn)',
    longestWaitTime: 'En Uzun Bekleme (sn)',
    fps: 'FPS',
    pdfTitle: 'ObservAI Analitik Raporu',
    generatedDate: 'Olusturma Tarihi',
    cameraField: 'Kamera',
    periodField: 'Donem',
    totalRecordsField: 'Toplam Kayit',
    allCameras: 'Tum Kameralar',
    allTime: 'Tum Zaman',
    now: 'Simdi',
    summarySection: 'Ozet Istatistikler',
    totalEntered: 'Toplam Giren',
    totalExited: 'Toplam Cikan',
    avgCurrent: 'Ort. Anlik Sayi',
    avgQueue: 'Ort. Kuyruk',
    detailSection: 'Ayrintili Analiz',
    detailTimestamp: 'Tarih',
    detailPeopleIn: 'Giren',
    detailPeopleOut: 'Cikan',
    detailCurrent: 'Anlik',
    detailQueue: 'Kuyruk',
    detailAvgWait: 'Ort.Bekl',
    detailMaxWait: 'Maks.Bekl',
    detailFps: 'FPS',
    moreRecords: (n) => `... ve ${n} kayit daha`,
    footer: 'ObservAI - Gercek Zamanli Kamera Analitik Platformu',
    csvFilename: (d) => `analitik_raporu_${d}.csv`,
    pdfFilename: (d) => `analitik_raporu_${d}.pdf`,
  },
  en: {
    timestamp: 'Timestamp',
    camera: 'Camera',
    peopleIn: 'People In',
    peopleOut: 'People Out',
    currentCount: 'Current Count',
    queueCount: 'Queue Count',
    avgWaitTime: 'Avg Wait Time (s)',
    longestWaitTime: 'Longest Wait Time (s)',
    fps: 'FPS',
    pdfTitle: 'ObservAI Analytics Report',
    generatedDate: 'Generated',
    cameraField: 'Camera',
    periodField: 'Period',
    totalRecordsField: 'Total Records',
    allCameras: 'All Cameras',
    allTime: 'All Time',
    now: 'Now',
    summarySection: 'Summary Statistics',
    totalEntered: 'Total People Entered',
    totalExited: 'Total People Exited',
    avgCurrent: 'Average Current Count',
    avgQueue: 'Average Queue Count',
    detailSection: 'Detailed Analytics',
    detailTimestamp: 'Timestamp',
    detailPeopleIn: 'People In',
    detailPeopleOut: 'People Out',
    detailCurrent: 'Current',
    detailQueue: 'Queue',
    detailAvgWait: 'Avg Wait',
    detailMaxWait: 'Max Wait',
    detailFps: 'FPS',
    moreRecords: (n) => `... and ${n} more records`,
    footer: 'Generated by ObservAI - Real-time Camera Analytics Platform',
    csvFilename: (d) => `analytics_export_${d}.csv`,
    pdfFilename: (d) => `analytics_report_${d}.pdf`,
  },
};

/**
 * Choose locale for the request. Order:
 *   1. ?lang=tr|en query param (explicit override)
 *   2. req.user.locale (when auth middleware exposes it — not wired yet)
 *   3. Accept-Language header — `tr*` -> tr, anything else -> en
 *   4. Default 'en'
 */
export function detectExportLocale(req: Request): ExportLocale {
  const q = String((req.query as Record<string, unknown>)?.lang ?? '').toLowerCase();
  if (q === 'tr' || q === 'en') return q;

  const userLocale = (req as Request & { user?: { locale?: string } }).user?.locale;
  if (userLocale === 'tr' || userLocale === 'en') return userLocale;

  const al = String(req.headers['accept-language'] ?? '').toLowerCase();
  if (al.startsWith('tr')) return 'tr';
  return 'en';
}
